### ISSUE TITLE
vue-tsc can not find vue files if module resolution is node12 or nodenext

### ISSUE THREAD

**Issue by kalvenschraut** [johnsoncodehk/volar#1394]
Reproduction can be found [here](https://github.com/RtVision/vue-tsc-nodenext-repro)

I have been trying to migrate my codebase to use typescripts new esm modules and for that I need to use node12 or nodenext module resolution. Everything seems to work fine, but due to typescript needing extensions to correctly resolve files now,  it appears vue-tsc is unable to find the vue files anymore. I did notice having `vue.js` did fix the issue for vue-tsc, but then I can't build with vite. 

I can't seem to find any other alternative solutions to this problem, maybe I have to change something in my code base?

A possible solution to the problem maybe  changing the file import path to vue.js with vue-tsc before calling tsc? If this is the desired direction, and if pointed in the right direction I can take a look at doing a PR.

**Comment by kalvenschraut** [comment]
This seems to affect the module resolution in my editor also.

**Comment by kalvenschraut** [comment]
Found a workaround, which is using.vue.js everywhere and added the below to my vite config

```ts
{
    resolve: {
      // seems first matched alias is used, so handle case where using @ alias and vue file has a .vue.js extension
      alias: [{
        find: /^@\/(.*)\.vue\.js$/,
        replacement: `${resolve('src')}/$1.vue`
      }, {
        find: /^(.*)\.vue\.js$/, 
        replacement: `$1.vue`
      }, {
        find: '@',
        replacement: resolve('src')
      }]
    }
}
```

**Comment by pwang2** [comment]
using latest volar after merge #1542 ,  everything works fine but language server will complain.   Have I missed anything? 

![image](https://user-images.githubusercontent.com/1592014/205523966-2a3a7757-bdb1-49de-83a8-6bcd60787ca0.png)

**Comment by pwang2** [comment]
still quite confusing but fixed by adding `env.d.ts` with a generic vue module definition and include in `tsconfig.json`
```typescript
/// <reference types="vite/client" />
/// <reference types="vue/macros-global" />

declare module "*.vue" {
  import { DefineComponent } from "vue"
  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/ban-types
  const component: DefineComponent<{}, {}, any>
  export default component
}
```

**Comment by pwang2** [comment]
After adding the dumb module hack, in `main.ts`, if you go to definition of `App.vue` import, it takes you to the `env.d.ts` dumb module. 

In `App.vue`, if you go to definition of `HelloWorld.vue`, it takes you to the actual file which is more desired. 

So still, it is not quite a complete solution.

**Comment by johnsoncodehk** [comment]
@pwang2 see https://github.com/johnsoncodehk/volar/issues/1897#issuecomment-1257149754

**Comment by pwang2** [comment]
@johnsoncodehk ,  Takeover mode works for me in Neovim.  Thanks!  Great work on volar to make everyone's life better and better. 🙌

**Comment by AlansCodeLog** [comment]
Is nodenext resolution supposed to work with just the `.vue` extension (I can't seem to get that working, and takeover is enabled) or do we have to specify `.vue.js`?

**Comment by kalvenschraut** [comment]
it is suppose to but @johnsoncodehk it appears since typescript 5.0 I have to refer to ,vue.js again. 
Update my original repo to typescript 5.0  and can be used to recreate.

![image](https://user-images.githubusercontent.com/30308012/233135828-e2198416-ba8e-42d9-b67b-a89142bc7e4f.png)

**Comment by johnsoncodehk** [comment]
It should be fixed by #2555

**Comment by kalvenschraut** [comment]
looks like #2555 has been out already? In my repo it is still a problem even with vue-tsc 1.4.
