### ISSUE TITLE
v0.24.x Make cpu too high and `ref` sugar in multi-tabs may not working

### ISSUE THREAD

**Issue by cutsin** [johnsoncodehk/volar#162]
Finally I rollback to v0.23.7 , and then everything is fine.

**Comment by johnsoncodehk** [comment]
Hi @cutsin, 0.24.0 has a performance bug and fixed in 0.24.3, can you try it if you not update yet? See: https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0243

**Comment by cutsin** [comment]
> Hi @cutsin, 0.24.0 has a performance bug and fixed in 0.24.3, can you try it if you not update yet? See: https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0243

Thanks for your quick reply.
Yes I tried 0.24.3 before, but problem still exists. 😅

**Comment by johnsoncodehk** [comment]
This problem has occurred in 0.24.0 begin?

I checked 0.24.0 commits but I can't found the reason... Will be very helpful if we can have a direct talking in Discord.

**Comment by cutsin** [comment]
> This problem has occurred in 0.24.0 begin?
> 
> I checked 0.24.0 commits but I can't found a possible reason... Will be very helpful if we can have a direct talking in Discord.

Okay... I'll try it later. 
But I'm pretty sure 0.24.0 has this problem, and `ref:` sugar's color render failed too.

And maybe it's due to VSCode or TypeScript?
This issue first occuried after a VSCode latest version (1.55.2) updated.

**Comment by johnsoncodehk** [comment]
Let focus on performance on this issue, ref sugar syntax token is different problem and please open a new issue to track.

I have fix a performance problem in 0.24.5, can you take a try?

**Comment by Liu-Ya** [comment]
> Let focus on performance on this issue, ref sugar syntax token is different problem and please open a new issue to track.
> 
> I have fix a performance issue in 0.24.5, can you take a try?

![image](https://user-images.githubusercontent.com/23520283/116195884-5edcdb80-a765-11eb-994b-70c254108476.png)

![image](https://user-images.githubusercontent.com/23520283/116195899-6308f900-a765-11eb-8b87-42a96cea97cf.png)

The CPU usage is still high, and I haven’t done anything at this time

**Comment by johnsoncodehk** [comment]
This is a serious problem, I will deal with it as soon as possible.

Please provide a profiling result, see: https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md

**Comment by Liu-Ya** [comment]
[CPU-20210427T152726.zip](https://github.com/johnsoncodehk/volar/files/6382696/CPU-20210427T152726.zip)

**Comment by johnsoncodehk** [comment]
> [CPU-20210427T152726.zip](https://github.com/johnsoncodehk/volar/files/6382696/CPU-20210427T152726.zip)

Thanks but this is vetur's profiling not volar. 😅
I will explanation how to make a volar's one later.

**Comment by Liu-Ya** [comment]
> > [CPU-20210427T152726.zip](https://github.com/johnsoncodehk/volar/files/6382696/CPU-20210427T152726.zip)
> 
> Thanks but this is vetur's profiling not volar. 😅
> I will explanation how to make a volar's one later.

sorry, I din't find the port of volar

**Comment by cutsin** [comment]
[CPU-20210427T081434.878Z.cpuprofile.zip](https://github.com/johnsoncodehk/volar/files/6383273/CPU-20210427T081434.878Z.cpuprofile.zip)
0.24.5, the problem is still here, it might be of some help

**Comment by johnsoncodehk** [comment]
Seem a regression to https://github.com/johnsoncodehk/volar/issues/100.

I tried [vue-next/sfc-playground](https://github.com/vuejs/vue-next/tree/master/packages/sfc-playground) on windows and mac, but it can't reproduce.

@cutsin it seem not a volar's profiling too...

Please check https://github.com/johnsoncodehk/volar/blob/master/.github/STEP_TO_PROFILING.md to profiling, I think Document server is the problem, you're only need to add localhost:6010. Thank you!

**Comment by cutsin** [comment]
That's so weird...
In debug mode, after some editing & compilation, high CPU usage can always be idle as expected... 😅

**Comment by johnsoncodehk** [comment]
Or a easier way... you can run debug mode on each commit between 0.23.7 ~ 0.24.0, to find which commit cause this problem. 😅

**Comment by johnsoncodehk** [comment]
Already fix initializing progress in 0.24.6, if server stuck on initializing you can check the progress bar is working as expected or not.

**Comment by cutsin** [comment]
But problem still here when I updated to release version 0.25.1 (VSCode v1.56.0)

**Comment by johnsoncodehk** [comment]
@cutsin can you see stuck on "Initializing Vue language features (xxx)"? Please click it if you see, and then check the progress bar is moving or not.

Please try to provide a minimal repro case, otherwise I can't check the problem at all. :/

**Comment by johnsoncodehk** [comment]
@TSmulkys checked the profile, it's seem has a big looping in [this code](https://github.com/johnsoncodehk/volar/blob/4be78060a1604efcfb40a38a92580653476a6a5c/packages/vscode-vue-languageservice/src/services/semanticTokens.ts#L176-L191), but don't know the reason yet.

@cutsin, @Liu-Ya, @TSmulkys will be helpful if you can provide these informations:

1. Your VSCode infos. (In VSCode menu: `Code > About Visual Studio Code`)
2. Is this problem occur first in 0.24.0 for you?
3. Is this problem only occur on published extension but not in debug mode?
4. Will this problem occur on open a no `<template>` vue file?
4.1. If no, will this problem occur on `App.vue` in [this template](https://github.com/johnsoncodehk/volar-starter/tree/html-token)?
4.2. If no, please show your `<template>` code if possible.

Thank you. 🙏

**Comment by johnsoncodehk** [comment]
Please try 0.25.3.

**Comment by TSmulkys** [comment]
For me **0.25.3** fixes loop problem, but code lens references is broken.
Almost same stack as @cutsin,  I just use ```<script lang="ts">``` & Linux Manjaro

**Comment by johnsoncodehk** [comment]
> but code lens references is broken and autocomplete do not work in pug template.

It's works for me, can you provide more detail or a repro case in a new issue?

**Comment by Liu-Ya** [comment]
@johnsoncodehk  not work for me 🤕
I only use `<script lang="ts">`,`<style lang="less">` and tsx

**Comment by johnsoncodehk** [comment]
@Liu-Ya It should not a same problem, please provide a profiling record otherwise I can't check.

**Comment by Liu-Ya** [comment]
> @Liu-Ya It should not a same problem, please provide a profiling record otherwise I can't check.

Sorry, I'm not find port for volar, how do i configure ?

**Comment by johnsoncodehk** [comment]
> Please provide a profiling result, see: https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md

@Liu-Ya does this not works for you? It you can't make it works, record a video to show how this happen is also helpful. (Please open a new issue to track)

**Comment by RomainLanz** [comment]
Hey there! 👋 

With `VSCode Insider` (latest release) and latest release of Volar, I keep having CPU spikes.
Even when I close VSCode, the Volar process keeps running and takes up to 3 CPU!

![image](https://user-images.githubusercontent.com/2793951/118490661-797bf200-b71e-11eb-9e16-37294564773d.png)

Here is the same output from the command-line to show which process is taking CPU.

```bash
  PID  PPID %MEM  %CPU ARGS
 3760     1  6.8  92.2 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) /Users/romainlanz/.vscode-insiders/extensions/johnsoncodehk.volar-0.25.4/node_modules/@volar/vscode-server/out/server.js --node-ipc --clientProcessId=3738
 4394     1  4.8  91.7 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) --nolazy --inspect=6009 /Users/romainlanz/.vscode-insiders/extensions/johnsoncodehk.volar-0.25.4/node_modules/@volar/vscode-server/out/server.js --node-ipc --clientProcessId=4375
 4395     1  4.8  91.1 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) --nolazy --inspect=6010 /Users/romainlanz/.vscode-insiders/extensions/johnsoncodehk.volar-0.25.4/node_modules/@volar/vscode-server/out/server.js --node-ipc --clientProcessId=4375
 ```
 
My project is running with Vue 3, TypeScript and few components are using the `setup` syntax.
What can I do to help you troubleshoot this issue?

**Comment by johnsoncodehk** [comment]
@RomainLanz I think this is `VSCode Insider` problem, because Volar HTML server unlikely to take up too much cpu. Please try non insider version VSCode.

**Comment by RomainLanz** [comment]
> @RomainLanz I think this is `VSCode Insider` problem, because Volar HTML server unlikely to take up too much cpu (It's possible for API server and Document server). Please try non insider version VSCode.

Yes, all good without the `Insider` version! I must have tried that before asking here. 😄

**Comment by cutsin** [comment]
It seems that the same problem reappeared in v0.25.13.
And Status Bar always showing: `Initalizing JS/TS language features`

**Comment by johnsoncodehk** [comment]
@cutsin can this problem reappeared when you disabled volar's TS plugin?

If yes, this is TS problem, please track https://github.com/microsoft/vscode/issues/124561.
If no, please open a new issue with reproduce infos because the problem unrelated to this issue.
