### ISSUE TITLE
Volar stop working after i upgrade volar version

### ISSUE THREAD

**Issue by MonsterPi13** [johnsoncodehk/volar#1782]
After i upgrade VSCode and Volar version, volar crashed.

VSCode version: 1.70.2
Volar version: 0.40.4

Error as below:
```
/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:8175
        ts.Debug.assert((getRootLength(fromDirectory) > 0) === (getRootLength(to) > 0), "Paths must either both be absolute or both be relative");
                 ^

Error: Debug Failure. False expression: Paths must either both be absolute or both be relative
    at Object.getRelativePathFromDirectory (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:8175:18)
    at Object.getTsBuildInfoEmitOutputFilePath (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:110032:55)
    at verifyProjectReferences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:119067:71)
    at verifyCompilerOptions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:118716:13)
    at Object.createProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:116912:9)
    at synchronizeHostData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:165063:26)
    at Object.getProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:165195:13)
    at Object.a [as isValidFile] (/Users/ruanpeng/.vscode/extensions/vue.volar-0.40.4-darwin-arm64/dist/node/server.js:576:14666)
    at /Users/ruanpeng/.vscode/extensions/vue.volar-0.40.4-darwin-arm64/dist/node/server.js:1123:4519
    at r (/Users/ruanpeng/.vscode/extensions/vue.volar-0.40.4-darwin-arm64/dist/node/server.js:1123:6966)
[Info  - 14:17:05] Connection to server got closed. Server will restart.
[Error - 14:17:09] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Debug Failure. False expression: Paths must either both be absolute or both be relative
  Code: -32603 
[Error - 14:17:23] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Debug Failure. False expression: Paths must either both be absolute or both be relative
  Code: -32603 

```
When i downgrade volar version to v0.4.0, it works well.

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/johnsoncodehk/volar/commit/984974377a1dae8cc8564fe7c3507ecb461eb48d.

**Comment by Radik24** [comment]
Hi,

I'm still getting ^^ error with `"vue-tsc": "^1.1.2"`. It's pretty annoying because I cannot find bugs.

Thanks

**Comment by albert0815** [comment]
We are experiencing the same error. Really hard to understand what is going on.

**Comment by baakeydow** [comment]
same here

**Comment by microHoffman** [comment]
I can confirm this error on vue-tsc v1.3.4 ... downgrading to v1.2.0 resolved this issue, but i have no idea why it happens...

**Comment by wangxdmm** [comment]
+1
