### ISSUE TITLE
html and pug formatter extra spaces

### ISSUE THREAD

**Issue by grofzero** [johnsoncodehk/volar#1784]
Hi,

I have a very simple SFC the template looks like this: <div>{{msg}}</div>.
I click Format document with Volar in VS Code and the formatter adds extra spaces after the first and before the last curly braces. That's ok, but when I press "Format document" again it adds one more space. It happens only twice with html but with pug every format adds those extra spaces again and again.

Volar version: 0.40.4

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/johnsoncodehk/volar/commit/92d6c2478e642b3ad5ed28073e16fc694d51d2a8.

**Comment by itzaks** [comment]
Hi! I'm currently on `v0.40.5` but this is still happening for me with pug. Each save adds a space to each side inside the `{{ }}` interpolations.

**Comment by johnsoncodehk** [comment]
@itzaks Will check it, you can use 0.39.5 for pug project for now.
