### ISSUE TITLE
volar & vue-tsc can't verify hyphenated component prop

### ISSUE THREAD

**Issue by Ericteen** [johnsoncodehk/volar#1970]
versions
volar: v1.0.3
vue-tsc: v1.0.3

## reproduction

```vue
// parent component
<exchange-code
    v-for="item in dataList"
    :key="item.id"
    :data-obj="item"
/>
```

```vue
// child component
<script lang="ts" setup>
type DataObject = {
  title: string
  name: string
}

defineProps<{ dataObj: DataObject }>()
</script>
```
when the parent component prop is hyphenated, volar will throw an error, and run vue-tsc throws the same one.
<img width="613" alt="volar error" src="https://user-images.githubusercontent.com/16686286/194802145-5b6ea1af-1f8a-4cf1-aa89-e663cbf36a7c.png">

<img width="669" alt="vue-tsc error" src="https://user-images.githubusercontent.com/16686286/194802460-3beb1205-aea5-4ec4-9913-f4a8ffade331.png">

while when I change the parent prop to kebab based, volar and vue-tsc works fine. No error throws.

```vue
// parent component
<exchange-code
    v-for="item in dataList"
    :key="item.id"
    :dataObj="item"
/>
```

**Comment by ldsenow** [comment]
I have the same issue as well after upgrading to 1.0.3.

**Comment by EvilEl** [comment]
please fix

**Comment by eugeeenius** [comment]
Just add this to `tsconfig.json`: `"vueCompilerOptions": {
    "dataAttributes": []
  }`

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/johnsoncodehk/volar/commit/761f386af8e61067037ce0d65ff7c9d95c57923e

**Comment by dargmuesli** [comment]
I think this is a different issue. I still face the problem of having camelCase Props defined and vue-tsc complaining about accessing them as kebab-case.

```vue
<script setup lang="ts">
export interface Props {
  ariaLabel: string
}

withDefaults(defineProps<Props>(), {})
</script>
```

```html
<template>
  <Button
    aria-label="help"
  />
</template>
```

![image](https://user-images.githubusercontent.com/4778485/195232577-d5fe6ace-e75b-45ac-b72a-865fd3eb591d.png)

**Comment by johnsoncodehk** [comment]
@dargmuesli please try setting `vueCompilerOptions.htmlAttributes = []` in tsconfig.

**Comment by dargmuesli** [comment]
That worked. Thank you!

**Comment by dargmuesli** [comment]
Should I open an issue for that or is that intended behavior, @johnsoncodehk? If that config is intended to be set in my case, where do I find information about that?

**Comment by johnsoncodehk** [comment]
@dargmuesli We will add documentation for `vueCompilerOptions`.
