### ISSUE TITLE
Will Volar consider supporting Component Data interface like vetur for users to configure code hints?

### ISSUE THREAD

**Issue by Hgwxxdd** [johnsoncodehk/volar#418]
https://vuejs.github.io/vetur/guide/component-data.html

Will Volar consider supporting this feature?

**Comment by johnsoncodehk** [comment]
No, this is one of the features that Volar deliberately avoids. It will force the third-party librarys to write specific files in order to support specific IDE plugins.

If you write your components with `lang="ts"`, you will get native TS hints of components without additional configuration.

**Comment by philfontaine** [comment]
@johnsoncodehk What exactly is your take/solution for all the people who are using UI libraries like Vuetify, Quasar, etc. ? When using these libraries, the normal approach is to let these libraries auto import these components for you, so that you can write a bunch of <q-btn>, <q-input> etc. without having to import them in every single component you write.

I understand you made that choice for a reason, but without a solution it makes switching to volar a no-go.

**Comment by johnsoncodehk** [comment]
Are you talking about the definition of global components?

If the library defines the GlobalComponents interface, users can directly get tag prompts like `<q-btn>`, `<q-input>`. (May also need to set `types` option of tsconfig)

If the library does not have a GlobalComponents interface, but provides a type definition of components, you can define the GlobalComponents interface yourself.

See https://github.com/johnsoncodehk/volar#using.

**Comment by soulsam480** [comment]
@philfontaine Hi, were you able to make it work with quasar ?

**Comment by philfontaine** [comment]
Nope, I got busy and I didn't really try

**Comment by soulsam480** [comment]
@philfontaine sorry, figured it out. For anyone coming here for quasar paste this in `component.d.ts`
```ts
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    QAjaxBar: DefineComponent<InstanceType<typeof import('quasar')['QAjaxBar']>>;

    QAvatar: DefineComponent<InstanceType<typeof import('quasar')['QAvatar']>>;

    QBadge: DefineComponent<InstanceType<typeof import('quasar')['QBadge']>>;

    QBanner: DefineComponent<InstanceType<typeof import('quasar')['QBanner']>>;

    QBar: DefineComponent<InstanceType<typeof import('quasar')['QBar']>>;

    QBreadcrumbs: DefineComponent<InstanceType<typeof import('quasar')['QBreadcrumbs']>>;

    QBreadcrumbsEl: DefineComponent<InstanceType<typeof import('quasar')['QBreadcrumbsEl']>>;

    QBtnDropdown: DefineComponent<InstanceType<typeof import('quasar')['QBtnDropdown']>>;

    QBtnGroup: DefineComponent<InstanceType<typeof import('quasar')['QBtnGroup']>>;

    QBtnToggle: DefineComponent<InstanceType<typeof import('quasar')['QBtnToggle']>>;

    QBtn: DefineComponent<InstanceType<typeof import('quasar')['QBtn']>>;

    QCard: DefineComponent<InstanceType<typeof import('quasar')['QCard']>>;

    QCardActions: DefineComponent<InstanceType<typeof import('quasar')['QCardActions']>>;

    QCardSection: DefineComponent<InstanceType<typeof import('quasar')['QCardSection']>>;

    QCarousel: DefineComponent<InstanceType<typeof import('quasar')['QCarousel']>>;

    QCarouselControl: DefineComponent<InstanceType<typeof import('quasar')['QCarouselControl']>>;

    QCarouselSlide: DefineComponent<InstanceType<typeof import('quasar')['QCarouselSlide']>>;

    QChatMessage: DefineComponent<InstanceType<typeof import('quasar')['QChatMessage']>>;

    QCheckbox: DefineComponent<InstanceType<typeof import('quasar')['QCheckbox']>>;

    QChip: DefineComponent<InstanceType<typeof import('quasar')['QChip']>>;

    QCircularProgress: DefineComponent<InstanceType<typeof import('quasar')['QCircularProgress']>>;

    QColor: DefineComponent<InstanceType<typeof import('quasar')['QColor']>>;

    QDate: DefineComponent<InstanceType<typeof import('quasar')['QDate']>>;

    QDialog: DefineComponent<InstanceType<typeof import('quasar')['QDialog']>>;

    QDrawer: DefineComponent<InstanceType<typeof import('quasar')['QDrawer']>>;

    QEditor: DefineComponent<InstanceType<typeof import('quasar')['QEditor']>>;

    QExpansionItem: DefineComponent<InstanceType<typeof import('quasar')['QExpansionItem']>>;

    QFab: DefineComponent<InstanceType<typeof import('quasar')['QFab']>>;

    QFabAction: DefineComponent<InstanceType<typeof import('quasar')['QFabAction']>>;

    QField: DefineComponent<InstanceType<typeof import('quasar')['QField']>>;

    QFile: DefineComponent<InstanceType<typeof import('quasar')['QFile']>>;

    QFooter: DefineComponent<InstanceType<typeof import('quasar')['QFooter']>>;

    QForm: DefineComponent<InstanceType<typeof import('quasar')['QForm']>>;

    QFormChildMixin: DefineComponent<InstanceType<typeof import('quasar')['QFormChildMixin']>>;

    QHeader: DefineComponent<InstanceType<typeof import('quasar')['QHeader']>>;

    QIcon: DefineComponent<InstanceType<typeof import('quasar')['QIcon']>>;

    QImg: DefineComponent<InstanceType<typeof import('quasar')['QImg']>>;

    QInfiniteScroll: DefineComponent<InstanceType<typeof import('quasar')['QInfiniteScroll']>>;

    QInnerLoading: DefineComponent<InstanceType<typeof import('quasar')['QInnerLoading']>>;

    QInput: DefineComponent<InstanceType<typeof import('quasar')['QInput']>>;

    QIntersection: DefineComponent<InstanceType<typeof import('quasar')['QIntersection']>>;

    QItem: DefineComponent<InstanceType<typeof import('quasar')['QItem']>>;

    QItemLabel: DefineComponent<InstanceType<typeof import('quasar')['QItemLabel']>>;

    QItemSection: DefineComponent<InstanceType<typeof import('quasar')['QItemSection']>>;

    QList: DefineComponent<InstanceType<typeof import('quasar')['QList']>>;

    QKnob: DefineComponent<InstanceType<typeof import('quasar')['QKnob']>>;

    QLayout: DefineComponent<InstanceType<typeof import('quasar')['QLayout']>>;

    QLinearProgress: DefineComponent<InstanceType<typeof import('quasar')['QLinearProgress']>>;

    QMarkupTable: DefineComponent<InstanceType<typeof import('quasar')['QMarkupTable']>>;

    QMenu: DefineComponent<InstanceType<typeof import('quasar')['QMenu']>>;

    QNoSsr: DefineComponent<InstanceType<typeof import('quasar')['QNoSsr']>>;

    QOptionGroup: DefineComponent<InstanceType<typeof import('quasar')['QOptionGroup']>>;

    QPageScroller: DefineComponent<InstanceType<typeof import('quasar')['QPageScroller']>>;

    QPageSticky: DefineComponent<InstanceType<typeof import('quasar')['QPageSticky']>>;

    QPage: DefineComponent<InstanceType<typeof import('quasar')['QPage']>>;

    QPageContainer: DefineComponent<InstanceType<typeof import('quasar')['QPageContainer']>>;

    QPagination: DefineComponent<InstanceType<typeof import('quasar')['QPagination']>>;

    QParallax: DefineComponent<InstanceType<typeof import('quasar')['QParallax']>>;

    QPopupEdit: DefineComponent<InstanceType<typeof import('quasar')['QPopupEdit']>>;

    QPopupProxy: DefineComponent<InstanceType<typeof import('quasar')['QPopupProxy']>>;

    QPullToRefresh: DefineComponent<InstanceType<typeof import('quasar')['QPullToRefresh']>>;

    QRadio: DefineComponent<InstanceType<typeof import('quasar')['QRadio']>>;

    QRange: DefineComponent<InstanceType<typeof import('quasar')['QRange']>>;

    QRating: DefineComponent<InstanceType<typeof import('quasar')['QRating']>>;

    QResizeObserver: DefineComponent<InstanceType<typeof import('quasar')['QResizeObserver']>>;

    QResponsive: DefineComponent<InstanceType<typeof import('quasar')['QResponsive']>>;

    QScrollArea: DefineComponent<InstanceType<typeof import('quasar')['QScrollArea']>>;

    QScrollObserver: DefineComponent<InstanceType<typeof import('quasar')['QScrollObserver']>>;

    QSelect: DefineComponent<InstanceType<typeof import('quasar')['QSelect']>>;

    QSeparator: DefineComponent<InstanceType<typeof import('quasar')['QSeparator']>>;

    QSkeleton: DefineComponent<InstanceType<typeof import('quasar')['QSkeleton']>>;

    QSlideItem: DefineComponent<InstanceType<typeof import('quasar')['QSlideItem']>>;

    QSlideTransition: DefineComponent<InstanceType<typeof import('quasar')['QSlideTransition']>>;

    QSlider: DefineComponent<InstanceType<typeof import('quasar')['QSlider']>>;

    QSpace: DefineComponent<InstanceType<typeof import('quasar')['QSpace']>>;

    QSpinner: DefineComponent<InstanceType<typeof import('quasar')['QSpinner']>>;

    QSpinnerAudio: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerAudio']>>;

    QSpinnerBall: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerBall']>>;

    QSpinnerBars: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerBars']>>;

    QSpinnerBox: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerBox']>>;

    QSpinnerClock: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerClock']>>;

    QSpinnerComment: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerComment']>>;

    QSpinnerCube: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerCube']>>;

    QSpinnerDots: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerDots']>>;

    QSpinnerFacebook: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerFacebook']>>;

    QSpinnerGears: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerGears']>>;

    QSpinnerGrid: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerGrid']>>;

    QSpinnerHearts: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerHearts']>>;

    QSpinnerHourglass: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerHourglass']>>;

    QSpinnerInfinity: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerInfinity']>>;

    QSpinnerIos: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerIos']>>;

    QSpinnerOrbit: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerOrbit']>>;

    QSpinnerOval: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerOval']>>;

    QSpinnerPie: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerPie']>>;

    QSpinnerPuff: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerPuff']>>;

    QSpinnerRadio: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerRadio']>>;

    QSpinnerRings: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerRings']>>;

    QSpinnerTail: DefineComponent<InstanceType<typeof import('quasar')['QSpinnerTail']>>;

    QSplitter: DefineComponent<InstanceType<typeof import('quasar')['QSplitter']>>;

    QStep: DefineComponent<InstanceType<typeof import('quasar')['QStep']>>;

    QStepper: DefineComponent<InstanceType<typeof import('quasar')['QStepper']>>;

    QStepperNavigation: DefineComponent<
      InstanceType<typeof import('quasar')['QStepperNavigation']>
    >;

    QTabPanel: DefineComponent<InstanceType<typeof import('quasar')['QTabPanel']>>;

    QTabPanels: DefineComponent<InstanceType<typeof import('quasar')['QTabPanels']>>;

    QTable: DefineComponent<InstanceType<typeof import('quasar')['QTable']>>;

    QTd: DefineComponent<InstanceType<typeof import('quasar')['QTd']>>;

    QTh: DefineComponent<InstanceType<typeof import('quasar')['QTh']>>;

    QTr: DefineComponent<InstanceType<typeof import('quasar')['QTr']>>;

    QRouteTab: DefineComponent<InstanceType<typeof import('quasar')['QRouteTab']>>;

    QTab: DefineComponent<InstanceType<typeof import('quasar')['QTab']>>;

    QTabs: DefineComponent<InstanceType<typeof import('quasar')['QTabs']>>;

    QTime: DefineComponent<InstanceType<typeof import('quasar')['QTime']>>;

    QTimeline: DefineComponent<InstanceType<typeof import('quasar')['QTimeline']>>;

    QTimelineEntry: DefineComponent<InstanceType<typeof import('quasar')['QTimelineEntry']>>;

    QToggle: DefineComponent<InstanceType<typeof import('quasar')['QToggle']>>;

    QToolbar: DefineComponent<InstanceType<typeof import('quasar')['QToolbar']>>;

    QToolbarTitle: DefineComponent<InstanceType<typeof import('quasar')['QToolbarTitle']>>;

    QTooltip: DefineComponent<InstanceType<typeof import('quasar')['QTooltip']>>;

    QTree: DefineComponent<InstanceType<typeof import('quasar')['QTree']>>;

    QUploader: DefineComponent<InstanceType<typeof import('quasar')['QUploader']>>;

    QUploaderAddTrigger: DefineComponent<
      InstanceType<typeof import('quasar')['QUploaderAddTrigger']>
    >;

    QVideo: DefineComponent<InstanceType<typeof import('quasar')['QVideo']>>;

    QVirtualScroll: DefineComponent<InstanceType<typeof import('quasar')['QVirtualScroll']>>;
  }
}

export {};
```
a small script for this is 
```js
try {
// s = a string of all quasar component names separated by newline
  const components = s
    .split('\n')
    .reduce((arr, component) => {
      if (!component) return arr;
      console.log('extracting', component);

      arr.push(`
     ${component} : DefineComponent<InstanceType<typeof import('quasar')['${component}']>>;
    `);
      return arr;
    }, [])
    .join('\n');

  const built = `
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ${components}
  }
}

export {};
`;

  writeFileSync('./src/components.d.ts', built);
} catch (error) {
  console.log(error);
}
```

**Comment by johnsoncodehk** [comment]
@soulsam480 thanks for the share! But it seem component props type-checking / intellisense not work in this definition, I think there is still room for improvement.

**Comment by soulsam480** [comment]
> @soulsam480 thanks for the share! But it seem component props type-checking / intellisense not work in this definition, I think there is still room for improvement.

Hi, yes that's true. The quasar team is working on supporting volar natively with proper ts definitions for components. This is just a workaround to achieve manageable autocompletion.

**Comment by johnsoncodehk** [comment]
The component type is not completely correct, but some props type-checking / auto-complete is working.

<img width="807" alt="螢幕截圖 2021-09-14 上午1 54 46" src="https://user-images.githubusercontent.com/16279759/133132937-dbeb9968-5521-470e-944c-869f55c95388.png">

```ts
import { ComponentConstructor } from 'quasar';

type Quasar = typeof import('quasar');
type QuasarComponentNames = keyof { [K in keyof Quasar as (Quasar)[K] extends ComponentConstructor<infer _> ? K : never]: any };
type QuasarComponents = Pick<Quasar, QuasarComponentNames>;
type QuasarFuncationalComponents = { [K in keyof QuasarComponents]: Quasar[K] extends ComponentConstructor<infer C> ? (props: Partial<C>) => void : never };

declare module '@vue/runtime-core' {
	export interface GlobalComponents extends QuasarFuncationalComponents { }
}
```

**Comment by soulsam480** [comment]
> The component type is not completely correct, but some props type-checking / auto-complete is working.
> 
> <img alt="螢幕截圖 2021-09-14 上午1 54 46" width="807" src="https://user-images.githubusercontent.com/16279759/133132937-dbeb9968-5521-470e-944c-869f55c95388.png">
> 
> ```ts
> import { ComponentConstructor } from 'quasar';
> 
> type Quasar = typeof import('quasar');
> type QuasarComponentNames = keyof { [K in keyof Quasar as (Quasar)[K] extends ComponentConstructor<infer _> ? K : never]: any };
> type QuasarComponents = Pick<Quasar, QuasarComponentNames>;
> type QuasarFuncationalComponents = { [K in keyof QuasarComponents]: Quasar[K] extends ComponentConstructor<infer C> ? (props: Partial<C>) => void : never };
> 
> declare module '@vue/runtime-core' {
> 	export interface GlobalComponents extends QuasarFuncationalComponents { }
> }
> ```

I know official support is coming but this is an error that I get from the above approach

```
'__VLS_31' cannot be used as a JSX component.
  Its return type 'void' is not a valid JSX element.ts(2786)
(property) 'q-option-group': (props: Partial<QOptionGroup>) => void
```

**Comment by johnsoncodehk** [comment]
@soulsam480 it should be fixed in 0.27.29. (#553)

**Comment by johnsoncodehk** [comment]
@hinogi yes I make something wrong :S, you can change `(props: Partial<C>) => void` to `(props: Partial<C>) => any` to fix.

**Comment by douglasg14b** [comment]
The example here: https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features

Doesn't seem to work in Vue2?

```ts
// components.d.ts
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
```

I still get no autocomplete or API info for router links or views.

How is this supposed to work for larger frameworks like Vuetify??

**Comment by q1uxu** [comment]
> The example here: https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features
> 
> Doesn't seem to work in Vue2?
> 
> ```ts
> // components.d.ts
> declare module '@vue/runtime-core' {
>   export interface GlobalComponents {
>     RouterLink: typeof import('vue-router')['RouterLink']
>     RouterView: typeof import('vue-router')['RouterView']
>   }
> }
> 
> export {}
> ```
> 
> I still get no autocomplete or API info for router links or views.
> 
> How is this supposed to work for larger frameworks like Vuetify in Vue 2? Is additional configuration required outside of the above?

The config of vue2.x  is different from vue3.x.
```typescript
// components.d.ts
declare module '@vue/runtime-core' {  // Vue 3
// declare module 'vue' {   // Vue 2.7
// declare module '@vue/runtime-dom' {  // Vue <= 2.6.14
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
```
