### ISSUE TITLE
Emmet doesn't work properly

### ISSUE THREAD

**Issue by aantipov** [johnsoncodehk/volar#716]
In raw html files typing abbreviations invokes emmet suggestions and live-preview:
![CleanShot 2021-11-21 at 13 20 33](https://user-images.githubusercontent.com/427621/142761547-55bac263-e36c-41da-86d2-507721baffd9.gif)

In `<template>` section of Vue file there is not emmet suggestions nor live-preview:
![CleanShot 2021-11-21 at 13 24 30](https://user-images.githubusercontent.com/427621/142761724-91a9162a-8c40-4dc7-96bf-0930185d6c39.gif)

I believe such "non-full" support of emmet is the cause of emmet not working properly together with VSCodeVim extension.
Whenever an abbreviation is expanded, VSCodeVim goes into "Normal" mode => the following typing doesn't work as expected
![CleanShot 2021-11-21 at 13 30 41](https://user-images.githubusercontent.com/427621/142761958-c46f3898-3748-4c1f-b9db-858f544e6caa.gif)

**Comment by sethidden** [comment]
I can't reproduce this with and without vscodevim — emmet completions appear normally in both.
See also https://github.com/johnsoncodehk/volar/discussions/692

Can you disable all extensions but Volar and Vscodevim then try Emmet in a `yarn create vite` project (as mentioned in the discussion linked above)?

**Comment by johnsoncodehk** [comment]
This may be related to your VSCode settings. Could you backup and completely clear your VSCode settings and try again?

You can use `Preferences: Open Settings (JSON)` and `Preferences: Open Workspace Settings (JSON)` commands to check your settings.

**Comment by aantipov** [comment]
I just tried github.dev in incognito window with a freshly created Github account and the problem is still there.
Could you try this file https://github.dev/vuejs/blog/blob/master/.vitepress/theme/Layout.vue ?

![image](https://user-images.githubusercontent.com/427621/142827778-1c3cbd90-8662-42c9-b60d-62e5d4f20593.png)

So it seems to me not the problem with settings or extensions.
Maybe I need to specify some Emmet settings to properly treat Vue files?

**Comment by johnsoncodehk** [comment]
We only support syntax highlight in web IDE for now, please track #612.

**Comment by geirmarius** [comment]
@aantipov I had the same problem just now, but it somehow solved itself when I downgraded one version, then upgraded back to the newest. Removing and reinstalling would assumable have the same effect.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/3246152/142838910-f51c69d3-543e-4aa0-b526-4ebf4e50d9ea.png">

No idea what the issue was tho, as it worked before the weekend, and when I came back today it didn't.

**Comment by johnsoncodehk** [comment]
@geirmarius Can you always reproduce it based on some steps?

**Comment by geirmarius** [comment]
Not sure what I can do to reproduce it sorry. Seems whatever I try it works now.
When it happened, it also didn't detect any tsconfig (at least according to the status bar on the bottom right of vs code), if that helps.

**Comment by aantipov** [comment]
I created an new mac account, installed a fresh VSCode+Volar
Tried Vue files - the problem is the same. 
> but it somehow solved itself when I downgraded one version, then upgraded back to the newest.

I tried different versions of the extension. It didn't help unfortunately

>it also didn't detect any tsconfig

Confirm. Same to me 
![image](https://user-images.githubusercontent.com/427621/142845407-66ca900d-7813-465f-8208-c57e4f9bbd02.png)

I also tried the following Emmet settings. Didn't help either 
![image](https://user-images.githubusercontent.com/427621/142845555-b87c7b51-e3d5-479a-9351-2f37d6b52f65.png)

**Comment by johnsoncodehk** [comment]
I tried delete tsconfig.json in https://github.com/johnsoncodehk/volar-starter to make `No tsconfig` status but can't reproduce.

@aantipov did you also tried clear your settings?

**Comment by aantipov** [comment]
Ok, it works in Volar starter.
And now I see that it works in some vue files and doesn't work in others.

If you clone my repo https://github.com/aantipov/moiva, then you most probably will notice the same:
1. Emmet works in Vue files under `src/` folder and tsconfig is found
2. Emmet doesn't work under `blog` folder and has `No tsconfig`

If you clone https://github.com/vuejs/blog, then Emmet won't work under `.vitepress` folder

**Comment by johnsoncodehk** [comment]
@aantipov thanks for your repro case, this is expected behavior consistent with TS, you need to add `"blog/**/*.vue", "blog/.vitepress/**/*.vue"` to the tsconfig's include option.

**Comment by aantipov** [comment]
Didn't know that tsconfig could affect the way emmet works.
The problem is fixed now. Thanks 🙏

**Comment by d4g0** [comment]
Still dosen't work for me, turn off Vetur and turn on Volar, Emmet goes away, turn off Volar and turn on Vetur, and Emmet is back.

**Comment by abitwhy** [comment]
@johnsoncodehk
> I tried delete tsconfig.json in https://github.com/johnsoncodehk/volar-starter to make `No tsconfig` status but can't reproduce.
> 
> @aantipov did you also tried clear your settings?

It still doesn't work for me. No Emmet suggestions appear(although `triggerExpansionOnTab` still works if it turns on).

What do you mean about **work**? Does the following Emmet syntax work?

- Multiple `div*2`
- Content `div{0}` (numberic content)

**Comment by abitwhy** [comment]
@aantipov 
> Didn't know that tsconfig could affect the way emmet works. The problem is fixed now. Thanks 🙏

I think this conclusion lacks credibility, the problem must be with Volar because the problem didn't appear on Vetur with the same Emmet setting and tsconfig.json.

**Comment by abitwhy** [comment]
# Solution

- Setting UI

1. Search `emmet.includeLanguages`
2. Add `vue:html`
   *official example `vue-html:html` didn't work, don't knwon why.*

**OR**

- Setting File 

``` json
"emmet.includeLanguages": {
  "vue": "html"
},
```
